[package]
name = "some"
version = "0.1.0"
edition = "2021"
authors = ["Sayed Anower <sayed.anower.17.2@gmail.com>"]
description = ""
license = "MIT"
readme = "README.md"

[dependencies]
fr-search = "0.1"
tokio = { version = "1", features = ["full"] }
sonyflake = "0.5"
serde = { version = "1.0", features = ["derive"] }